[package]
name = "fphoto-renamer-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
toml.workspace = true
fphoto_renamer_core = { path = "../core" }
